config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
  validates :name, presence: true
  validates :address, presence: true
  validates :description, presence: true
  validates :price_per_night, presence: true
  validates :number_of_guests, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

  def new
    @flat = Flat.new
  end

  def edit
    @flat = Flat.find(params[:id])
  end

  def update
    @flat = Flat.find(params[:id])
    @flat.update(flat_params)

    # no need for app/views/restaurants/update.html.erb
    redirect_to flats_path
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def destroy
    @flat = Flat.find(params[:id])
    @flat.destroy

    # no need for app/views/restaurants/destroy.html.erb
    redirect_to flats_path
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to flats_path
    else
      render :new
    end
  end

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<%= form_for(flat) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :address %>
  <%= f.text_field :address %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.label :price_per_night %>
  <%= f.number_field :price_per_night %>
  <%= f.label :number_of_guests %>
  <%= f.number_field :number_of_guests %>
  <%= f.submit %>
<% end %>

app/views/flats/edit.html.erb
<h1>Edit a current flat</h1>
<%= render "form", flat: @flat %>

app/views/flats/index.html.erb
<h1>All Our Flats</h1>
<% @flats.each do |flat| %>

  <div class="container">
    <div class="row">
     <div class="col">
        <div class="card" style="width: 18rem;">
          <img class="card-img-top" src=".../100px180/" alt="Card image cap">
          <div class="card-body">
            <h5 class="card-title"><%= flat.name %></h5>
            <p class="card-text"><%= flat.address %></p>
            <p class="card-text"><%= flat.number_of_guests %></p>
            <p class="card-text"><%= flat.price_per_night %></p>
            <%= link_to "More info", flat_path(flat), class: "btn btn-primary"%>
            <%= link_to "Edit flat", edit_flat_path(flat), class: "btn btn-secondary"%>
            <%= link_to "Delete #{flat.name}",
            flat_path(flat),
            method: :delete,
            data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>
          </div>
        </div>
      </div>
      </div>
    </div>
<% end %>

app/views/flats/new.html.erb
<h1>Create a new flat</h1>
<%= render "form", flat: @flat %>

app/views/flats/show.html.erb
<h1>Flat</h1>
<%= @flat.name %>
<%= @flat.address %>
<%= @flat.description %>
<%= @flat.price_per_night %>
<%= @flat.number_of_guests %>
<hr>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <%= link_to "All flats", flats_path, class: "nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "Add new flat", new_flat_path, class: "nav-link"%>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Pricing</a>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#">Disabled</a>
          </li>
        </ul>
      </div>
    </nav>

    <%= yield %>
  </body>
</html>